import { AuctionListing, AuctionSource } from "../types";

function futureDate(daysFromNow: number, hours = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(d.getHours() + hours);
  return d.toISOString();
}

const DEMO_LISTINGS: AuctionListing[] = [
  // === KLARAVIK LISTINGS ===
  {
    id: "klaravik-1",
    title: "Volvo EC220E Grävmaskin 2019",
    description:
      "Volvo EC220E bandgrävmaskin, 22 ton, 4200 timmar. Utrustad med snabbfäste, extra hydraulik och LED-arbetsbelysning. Servad enligt tillverkarens rekommendationer.",
    currentBid: 785000,
    startingBid: 500000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1580901368919-7738efb0f87e?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.klaravik.se/objekt/volvo-ec220e",
    source: "klaravik",
    category: "Entreprenad",
    location: "Göteborg",
    endDate: futureDate(2, 14),
    bidCount: 23,
    condition: "Bra skick",
  },
  {
    id: "klaravik-2",
    title: "John Deere 6130R Traktor 2020",
    description:
      "John Deere 6130R med frontlastare, 130 hk, AutoQuad Plus växellåda. 2800 timmar. Luftkonditionering, GPS-förberedd.",
    currentBid: 920000,
    startingBid: 700000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1530267981375-f0de937f5f13?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.klaravik.se/objekt/john-deere-6130r",
    source: "klaravik",
    category: "Lantbruk",
    location: "Jönköping",
    endDate: futureDate(1, 10),
    bidCount: 31,
    condition: "Mycket bra skick",
  },
  {
    id: "klaravik-3",
    title: "Scania R520 Dragbil 2018",
    description:
      "Scania R520 V8 6x2, Euro 6, 520 hk. Retarder, navigering, kylskåp. Miltal: 380 000 km.",
    currentBid: 645000,
    startingBid: 400000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.klaravik.se/objekt/scania-r520",
    source: "klaravik",
    category: "Lastbilar",
    location: "Malmö",
    endDate: futureDate(3, 8),
    bidCount: 15,
    condition: "Bra skick",
  },
  {
    id: "klaravik-4",
    title: "Ponsse Scorpion Skördare 2017",
    description:
      "Ponsse Scorpion skördare, H7 aggregat, 14 200 timmar. Senast servad dec 2025. Ny kedja och svärd.",
    currentBid: 1250000,
    startingBid: 900000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1621460248083-6271cc4437a8?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.klaravik.se/objekt/ponsse-scorpion",
    source: "klaravik",
    category: "Skog",
    location: "Umeå",
    endDate: futureDate(4, 12),
    bidCount: 8,
    condition: "Acceptabelt skick",
  },
  {
    id: "klaravik-5",
    title: "CAT 320 Next Gen Grävmaskin 2021",
    description:
      "Caterpillar 320 Next Generation, 20 ton, 2100 timmar. Grade Control-förberedd. Mycket fint skick.",
    currentBid: 1100000,
    startingBid: 800000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.klaravik.se/objekt/cat-320",
    source: "klaravik",
    category: "Entreprenad",
    location: "Stockholm",
    endDate: futureDate(1, 6),
    bidCount: 42,
    condition: "Mycket bra skick",
  },
  {
    id: "klaravik-6",
    title: "Volvo FH16 750 Timmerfordon 2019",
    description:
      "Volvo FH16 750 hk 6x4, timmerbyggd med kran. Miltal: 290 000 km. I/Shift växellåda.",
    currentBid: 890000,
    startingBid: 600000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1586191582056-3189e85de7e0?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.klaravik.se/objekt/volvo-fh16",
    source: "klaravik",
    category: "Transport",
    location: "Sundsvall",
    endDate: futureDate(5, 9),
    bidCount: 11,
    condition: "Bra skick",
  },
  {
    id: "klaravik-7",
    title: "Komatsu WA320-8 Hjullastare 2020",
    description:
      "Komatsu WA320-8 hjullastare, 3.2 m3 skopa, 3600 timmar. Klimatanläggning, backkamera.",
    currentBid: 560000,
    startingBid: 350000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.klaravik.se/objekt/komatsu-wa320",
    source: "klaravik",
    category: "Entreprenad",
    location: "Linköping",
    endDate: futureDate(2, 16),
    bidCount: 19,
    condition: "Bra skick",
  },

  // === BLINTO LISTINGS ===
  {
    id: "blinto-1",
    title: "Liebherr LTM 1060 Mobilkran 2016",
    description:
      "Liebherr LTM 1060-3.1 mobilkran, 60 ton lyftkapacitet, 48m bom. Senaste besiktningen godkänd.",
    currentBid: 2100000,
    startingBid: 1500000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.blinto.se/auction/liebherr-ltm-1060",
    source: "blinto",
    category: "Entreprenad",
    location: "Västerås",
    endDate: futureDate(3, 10),
    bidCount: 5,
    condition: "Bra skick",
  },
  {
    id: "blinto-2",
    title: "Mercedes-Benz Actros 2551 Lastväxlare 2019",
    description:
      "Mercedes-Benz Actros 2551 6x2 lastväxlare, Euro 6, 510 hk. Miltal: 210 000 km. Fullt servicerad.",
    currentBid: 520000,
    startingBid: 350000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.blinto.se/auction/mb-actros-2551",
    source: "blinto",
    category: "Lastbilar",
    location: "Örebro",
    endDate: futureDate(2, 8),
    bidCount: 12,
    condition: "Bra skick",
  },
  {
    id: "blinto-3",
    title: "Hyundai HX235LCR Grävmaskin 2022",
    description:
      "Hyundai HX235LCR bandgrävmaskin, 25 ton, 1200 timmar. Reducerat svansutsving, perfekt för trånga utrymmen.",
    currentBid: 950000,
    startingBid: 700000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1580901368919-7738efb0f87e?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.blinto.se/auction/hyundai-hx235lcr",
    source: "blinto",
    category: "Entreprenad",
    location: "Karlstad",
    endDate: futureDate(1, 14),
    bidCount: 28,
    condition: "Mycket bra skick",
  },
  {
    id: "blinto-4",
    title: "Hilti verktygspaket - Borrhammare + Slipmaskin",
    description:
      "Hilti TE 70-ATC borrhammare och Hilti DG 150 slipmaskin. Inkl. väskor och tillbehör. Sparsamt använda.",
    currentBid: 18500,
    startingBid: 10000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1581147036324-c17ac41f9eab?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.blinto.se/auction/hilti-paket",
    source: "blinto",
    category: "Verktyg",
    location: "Norrköping",
    endDate: futureDate(0, 6),
    bidCount: 35,
    condition: "Bra skick",
  },
  {
    id: "blinto-5",
    title: "Manitou MT 1440 Teleskoplastare 2018",
    description:
      "Manitou MT 1440 Easy, 14m lyfthöjd, 4 ton lyftkapacitet. 3200 timmar. Fullt utrustad.",
    currentBid: 420000,
    startingBid: 280000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.blinto.se/auction/manitou-mt1440",
    source: "blinto",
    category: "Entreprenad",
    location: "Borås",
    endDate: futureDate(4, 11),
    bidCount: 9,
    condition: "Bra skick",
  },
  {
    id: "blinto-6",
    title: "Husqvarna FS 5000 D Golvfräs",
    description:
      "Husqvarna FS 5000 D diesel golvfräs/fogsåg. Klinga 500mm. Kör timmar: 480.",
    currentBid: 95000,
    startingBid: 60000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.blinto.se/auction/husqvarna-fs5000",
    source: "blinto",
    category: "Verktyg",
    location: "Helsingborg",
    endDate: futureDate(1, 18),
    bidCount: 14,
    condition: "Acceptabelt skick",
  },
  {
    id: "blinto-7",
    title: "Volvo L90H Hjullastare 2019",
    description:
      "Volvo L90H hjullastare, 2.8 m3 skopa, 4100 timmar. OptiShift, Comfort Drive Control.",
    currentBid: 680000,
    startingBid: 450000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.blinto.se/auction/volvo-l90h",
    source: "blinto",
    category: "Entreprenad",
    location: "Luleå",
    endDate: futureDate(3, 7),
    bidCount: 17,
    condition: "Mycket bra skick",
  },

  // === BUDI LISTINGS ===
  {
    id: "budi-1",
    title: "Apple MacBook Pro 16\" M3 Max - Konkursbo",
    description:
      "Apple MacBook Pro 16\" M3 Max, 36GB RAM, 1TB SSD. Från konkursbo, kvitto finns. Garanti kvar till 2026.",
    currentBid: 22500,
    startingBid: 15000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.budi.se/auction/macbook-pro-m3",
    source: "budi",
    category: "IT & Datorer",
    location: "Stockholm",
    endDate: futureDate(1, 4),
    bidCount: 67,
    condition: "Mycket bra skick",
  },
  {
    id: "budi-2",
    title: "Komplett restaurangkök - Industriutrustning",
    description:
      "Komplett restaurangkök inkl. rostfria arbetsbänkar, kylskåp, frys, ugn, spis, diskmaskin. Från nedlagd restaurang.",
    currentBid: 45000,
    startingBid: 20000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.budi.se/auction/restaurangkok",
    source: "budi",
    category: "Restaurang",
    location: "Malmö",
    endDate: futureDate(2, 12),
    bidCount: 14,
    condition: "Bra skick",
  },
  {
    id: "budi-3",
    title: "Makita verktygsset 18V - 12 delar",
    description:
      "Komplett Makita 18V LXT verktygsset, 12 maskiner inkl. 6st 5.0Ah batterier och dubbelladdare. Allt i systainer.",
    currentBid: 12800,
    startingBid: 8000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1581147036324-c17ac41f9eab?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.budi.se/auction/makita-set",
    source: "budi",
    category: "Verktyg",
    location: "Göteborg",
    endDate: futureDate(0, 8),
    bidCount: 41,
    condition: "Nyskick",
  },
  {
    id: "budi-4",
    title: "Konferensrumsmöbler - Fritz Hansen",
    description:
      "Komplett konferensrumsmöbel från Fritz Hansen. Bord 240x120cm + 10 stolar Series 7. Från konkursbo.",
    currentBid: 35000,
    startingBid: 15000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.budi.se/auction/fritz-hansen",
    source: "budi",
    category: "Inredning",
    location: "Stockholm",
    endDate: futureDate(3, 16),
    bidCount: 22,
    condition: "Bra skick",
  },
  {
    id: "budi-5",
    title: "Toyota Hilux 2.4 D-4D 4WD 2020",
    description:
      "Toyota Hilux Invincible, 2.4 D-4D, 150 hk, 4WD, automat. 68 000 km. Dragkrok, kåpa.",
    currentBid: 285000,
    startingBid: 200000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.budi.se/auction/toyota-hilux",
    source: "budi",
    category: "Fordon",
    location: "Uppsala",
    endDate: futureDate(2, 10),
    bidCount: 53,
    condition: "Bra skick",
  },
  {
    id: "budi-6",
    title: "Precor gym-paket - 15 maskiner",
    description:
      "Komplett Precor gym-paket med 15 styrketräningsmaskiner. Från nedlagt gym. Väl underhållna.",
    currentBid: 78000,
    startingBid: 40000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.budi.se/auction/precor-gym",
    source: "budi",
    category: "Övrigt",
    location: "Västra Götaland",
    endDate: futureDate(4, 8),
    bidCount: 7,
    condition: "Bra skick",
  },
  {
    id: "budi-7",
    title: "Samsung 75\" The Frame TV - 3 st",
    description:
      "3st Samsung 75\" The Frame QLED 4K TV (2024 modell). Från företagskonkurs. Originalförpackade.",
    currentBid: 28000,
    startingBid: 18000,
    currency: "SEK",
    imageUrl: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&h=400&fit=crop",
    images: [],
    url: "https://www.budi.se/auction/samsung-frame-tv",
    source: "budi",
    category: "IT & Datorer",
    location: "Jönköping",
    endDate: futureDate(1, 20),
    bidCount: 38,
    condition: "Nyskick",
  },
];

export function getDemoListings(
  sources?: AuctionSource[]
): AuctionListing[] {
  if (!sources || sources.length === 0) {
    return DEMO_LISTINGS;
  }
  return DEMO_LISTINGS.filter((l) => sources.includes(l.source));
}
